# Base Image
FROM node

# Working Directory
WORKDIR /usr/src/app

# 우선 node module들을 다운받는다.
# 이때 종속성에 대한 변동사항이 없었다면,
# 캐시되어 있는 이미지로 인해 속도가 개선된다.
COPY package*.json ./

RUN npm install

# 현재 디렉토리에 있는 모든 파일들을 컨테이너에 복사한다.
COPY ./ ./

CMD ["node", "server.js"]